### ISSUE TITLE
Add an "Add Tour" Dialog

### ISSUE THREAD

**Issue by Emile-Durkheim** [Nanogamer7/swen2-tour-planner#2]
- Should happen upon clicking "btnAddTour" in TourMenuController. 
- Should open a new window
- Ideally implement a mock TourRepository.addNewTour() method to the TourRepository
- Should refresh the ListView

**Comment by Nanogamer7** [comment]
> Should open a new window

Pop-up windows (as in actual windows) are not ideal in terms of usability. Instead maybe replace the detail view with a form view (see branch 'Beni')
