### ISSUE TITLE
Add an "Edit Tour" dialog

### ISSUE THREAD

**Issue by Emile-Durkheim** [Nanogamer7/swen2-tour-planner#4]
- Should ideally happen upon double-clicking an item in the ListView (idk how that could work, might be a pain in the ass)
- Otherwise, we could just add a button that opens a dialog with a dropdown of the tours and fields.
- Should ideally implement some mock TourRepository.updateTour() method
- Should trigger a refresh of the ListView

**Comment by Nanogamer7** [comment]
This form should ideally reuse the create tour form, but instead update it. Possible implementation: Have set the tour UUID, if its null: new tour; if non null: modify existing tour
